apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: azurerm_container_registry.container_registry
  description:  acrwikimaindev
  resourceName: acrwikimaindev
  resourceMode: data
  resource_group_name: rg-wiki-pangea-agent-main-dev
  resourceID: /subscriptions/fd3dc29c-3aef-4866-8f69-8ba0a9d31e42/resourceGroups/rg-wiki-pangea-agent-main-dev/providers/Microsoft.ContainerRegistry/registries/acrwikimaindev

spec:
  type: azurerm_container_registry
  owner: Marcos Cervantes
  system: Azure Terraform
  
---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: azurerm_log_analytics_workspace.law_workspace
  description:  law-wiki-pangea-agent-main-dev
  resourceName: law-wiki-pangea-agent-main-dev
  resourceMode: data
  resource_group_name: rg-wiki-pangea-agent-main-dev
  resourceID: /subscriptions/fd3dc29c-3aef-4866-8f69-8ba0a9d31e42/resourceGroups/rg-wiki-pangea-agent-main-dev/providers/Microsoft.OperationalInsights/workspaces/law-wiki-pangea-agent-main-dev

spec:
  type: azurerm_log_analytics_workspace
  owner: Marcos Cervantes
  system: Azure Terraform
  
---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: azurerm_postgresql_flexible_server.postgresql_server
  description:  psqls-wiki-pangea-agent-main-dev
  resourceName: psqls-wiki-pangea-agent-main-dev
  resourceMode: data
  resource_group_name: rg-wiki-pangea-agent-main-dev
  resourceID: /subscriptions/fd3dc29c-3aef-4866-8f69-8ba0a9d31e42/resourceGroups/rg-wiki-pangea-agent-main-dev/providers/Microsoft.DBforPostgreSQL/flexibleServers/psqls-wiki-pangea-agent-main-dev

spec:
  type: azurerm_postgresql_flexible_server
  owner: Marcos Cervantes
  system: Azure Terraform
  
---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: azurerm_resource_group.resource_group
  description:  rg-wiki-pangea-agent-main-dev
  resourceName: rg-wiki-pangea-agent-main-dev
  resourceMode: data
  resourceID: /subscriptions/fd3dc29c-3aef-4866-8f69-8ba0a9d31e42/resourceGroups/rg-wiki-pangea-agent-main-dev

spec:
  type: azurerm_resource_group
  owner: Marcos Cervantes
  system: Azure Terraform
  
---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: docker_registry_image.crawler
  description:  acrwikimaindev.azurecr.io/crawler:new
  resourceName: acrwikimaindev.azurecr.io/crawler:new
  resourceMode: managed
  resourceID: sha256:81a9c2b13ac48c9f352275182217ae6ba7f7c24e47a40d8ea57721cea53d4e32

spec:
  type: docker_registry_image
  owner: Marcos Cervantes
  system: Azure Terraform
  dependsOn: 
    - resource:default/azurerm_container_registry.container_registry
    - resource:default/azurerm_postgresql_flexible_server.postgresql_server

---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: docker_registry_image.metabase
  description:  acrwikimaindev.azurecr.io/metabase:new
  resourceName: acrwikimaindev.azurecr.io/metabase:new
  resourceMode: managed
  resourceID: sha256:a5596ac29c431178e36b2137887cdef1c2955caa5f16073bdede6fe431f5dd70

spec:
  type: docker_registry_image
  owner: Marcos Cervantes
  system: Azure Terraform
  dependsOn: 
    - resource:default/azurerm_container_registry.container_registry

---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: azapi_resource.app_crawler_azure_conf
  description:  aca-wiki-crawler
  resourceName: aca-wiki-crawler
  resourceMode: data
  resourceID: /subscriptions/fd3dc29c-3aef-4866-8f69-8ba0a9d31e42/resourceGroups/rg-wiki-pangea-agent-main-dev/providers/Microsoft.App/containerApps/aca-wiki-crawler

spec:
  type: azapi_resource
  owner: Marcos Cervantes
  system: Azure Terraform
  
---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: azapi_resource.app_metabase_azure_conf
  description:  aca-wiki-metabase
  resourceName: aca-wiki-metabase
  resourceMode: data
  resourceID: /subscriptions/fd3dc29c-3aef-4866-8f69-8ba0a9d31e42/resourceGroups/rg-wiki-pangea-agent-main-dev/providers/Microsoft.App/containerApps/aca-wiki-metabase

spec:
  type: azapi_resource
  owner: Marcos Cervantes
  system: Azure Terraform
  
---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: azapi_resource.app_crawler
  description:  aca-wiki-crawler
  resourceName: aca-wiki-crawler
  resourceMode: managed
  resourceID: /subscriptions/fd3dc29c-3aef-4866-8f69-8ba0a9d31e42/resourceGroups/rg-wiki-pangea-agent-main-dev/providers/Microsoft.App/containerApps/aca-wiki-crawler

spec:
  type: azapi_resource
  owner: Marcos Cervantes
  system: Azure Terraform
  dependsOn: 
    - resource:default/azurerm_container_registry.container_registry
    - resource:default/azurerm_log_analytics_workspace.law_workspace
    - resource:default/azurerm_postgresql_flexible_server.postgresql_server
    - resource:default/azurerm_resource_group.resource_group
    - resource:default/docker_registry_image.crawler
    - resource:default/azapi_resource.env_pangea_agent

---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: azapi_resource.app_metabase
  description:  aca-wiki-metabase
  resourceName: aca-wiki-metabase
  resourceMode: managed
  resourceID: /subscriptions/fd3dc29c-3aef-4866-8f69-8ba0a9d31e42/resourceGroups/rg-wiki-pangea-agent-main-dev/providers/Microsoft.App/containerApps/aca-wiki-metabase

spec:
  type: azapi_resource
  owner: Marcos Cervantes
  system: Azure Terraform
  dependsOn: 
    - resource:default/azurerm_container_registry.container_registry
    - resource:default/azurerm_log_analytics_workspace.law_workspace
    - resource:default/azurerm_postgresql_flexible_server.postgresql_server
    - resource:default/azurerm_resource_group.resource_group
    - resource:default/docker_registry_image.metabase
    - resource:default/azapi_resource.env_pangea_agent

---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: azapi_resource.env_pangea_agent
  description:  acae-wiki-pangea-agent-main-dev
  resourceName: acae-wiki-pangea-agent-main-dev
  resourceMode: managed
  resourceID: /subscriptions/fd3dc29c-3aef-4866-8f69-8ba0a9d31e42/resourceGroups/rg-wiki-pangea-agent-main-dev/providers/Microsoft.App/managedEnvironments/acae-wiki-pangea-agent-main-dev

spec:
  type: azapi_resource
  owner: Marcos Cervantes
  system: Azure Terraform
  dependsOn: 
    - resource:default/azurerm_log_analytics_workspace.law_workspace
    - resource:default/azurerm_resource_group.resource_group

---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: azurerm_container_registry.container_registry
  description:  acrwikimaindev
  resourceName: acrwikimaindev
  resourceMode: managed
  resource_group_name: rg-wiki-pangea-agent-main-dev
  resourceID: /subscriptions/fd3dc29c-3aef-4866-8f69-8ba0a9d31e42/resourceGroups/rg-wiki-pangea-agent-main-dev/providers/Microsoft.ContainerRegistry/registries/acrwikimaindev

spec:
  type: azurerm_container_registry
  owner: Marcos Cervantes
  system: Azure Terraform
  dependsOn: 
    - resource:default/azurerm_resource_group.resource_group

---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: azurerm_log_analytics_workspace.law_workspace
  description:  law-wiki-pangea-agent-main-dev
  resourceName: law-wiki-pangea-agent-main-dev
  resourceMode: managed
  resource_group_name: rg-wiki-pangea-agent-main-dev
  resourceID: /subscriptions/fd3dc29c-3aef-4866-8f69-8ba0a9d31e42/resourceGroups/rg-wiki-pangea-agent-main-dev/providers/Microsoft.OperationalInsights/workspaces/law-wiki-pangea-agent-main-dev

spec:
  type: azurerm_log_analytics_workspace
  owner: Marcos Cervantes
  system: Azure Terraform
  dependsOn: 
    - resource:default/azurerm_resource_group.resource_group

---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: azurerm_postgresql_flexible_server.postgresql_server
  description:  psqls-wiki-pangea-agent-main-dev
  resourceName: psqls-wiki-pangea-agent-main-dev
  resourceMode: managed
  resource_group_name: rg-wiki-pangea-agent-main-dev
  resourceID: /subscriptions/fd3dc29c-3aef-4866-8f69-8ba0a9d31e42/resourceGroups/rg-wiki-pangea-agent-main-dev/providers/Microsoft.DBforPostgreSQL/flexibleServers/psqls-wiki-pangea-agent-main-dev

spec:
  type: azurerm_postgresql_flexible_server
  owner: Marcos Cervantes
  system: Azure Terraform
  dependsOn: 
    - resource:default/azurerm_resource_group.resource_group

---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: azurerm_postgresql_flexible_server_database.psql_db_crawler
  description:  crawler
  resourceName: crawler
  resourceMode: managed
  resourceID: /subscriptions/fd3dc29c-3aef-4866-8f69-8ba0a9d31e42/resourceGroups/rg-wiki-pangea-agent-main-dev/providers/Microsoft.DBforPostgreSQL/flexibleServers/psqls-wiki-pangea-agent-main-dev/databases/crawler

spec:
  type: azurerm_postgresql_flexible_server_database
  owner: Marcos Cervantes
  system: Azure Terraform
  dependsOn: 
    - resource:default/azurerm_resource_group.resource_group
    - resource:default/azurerm_postgresql_flexible_server.postgresql_server

---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: azurerm_postgresql_flexible_server_database.psql_db_metabase
  description:  metabase
  resourceName: metabase
  resourceMode: managed
  resourceID: /subscriptions/fd3dc29c-3aef-4866-8f69-8ba0a9d31e42/resourceGroups/rg-wiki-pangea-agent-main-dev/providers/Microsoft.DBforPostgreSQL/flexibleServers/psqls-wiki-pangea-agent-main-dev/databases/metabase

spec:
  type: azurerm_postgresql_flexible_server_database
  owner: Marcos Cervantes
  system: Azure Terraform
  dependsOn: 
    - resource:default/azurerm_resource_group.resource_group
    - resource:default/azurerm_postgresql_flexible_server.postgresql_server

---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: azurerm_postgresql_flexible_server_firewall_rule.psql_fw_rule
  description:  psqls-wiki-pangea-agent-main-dev-fw-rule
  resourceName: psqls-wiki-pangea-agent-main-dev-fw-rule
  resourceMode: managed
  resourceID: /subscriptions/fd3dc29c-3aef-4866-8f69-8ba0a9d31e42/resourceGroups/rg-wiki-pangea-agent-main-dev/providers/Microsoft.DBforPostgreSQL/flexibleServers/psqls-wiki-pangea-agent-main-dev/firewallRules/psqls-wiki-pangea-agent-main-dev-fw-rule

spec:
  type: azurerm_postgresql_flexible_server_firewall_rule
  owner: Marcos Cervantes
  system: Azure Terraform
  dependsOn: 
    - resource:default/azurerm_resource_group.resource_group
    - resource:default/azurerm_postgresql_flexible_server.postgresql_server

---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: postgresql_grant.crawler_grant
  description:  crawler
  resourceName: crawler
  resourceMode: managed
  resourceID: crawler_db_user_crawler_database

spec:
  type: postgresql_grant
  owner: Marcos Cervantes
  system: Azure Terraform
  dependsOn: 
    - resource:default/azurerm_resource_group.resource_group
    - resource:default/azurerm_postgresql_flexible_server.postgresql_server
    - resource:default/azurerm_postgresql_flexible_server_database.psql_db_crawler
    - resource:default/azurerm_postgresql_flexible_server_firewall_rule.psql_fw_rule
    - resource:default/postgresql_role.crawler_role

---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: postgresql_grant.metabase_grant
  description:  metabase
  resourceName: metabase
  resourceMode: managed
  resourceID: metabase_db_user_metabase_database

spec:
  type: postgresql_grant
  owner: Marcos Cervantes
  system: Azure Terraform
  dependsOn: 
    - resource:default/azurerm_resource_group.resource_group
    - resource:default/azurerm_postgresql_flexible_server.postgresql_server
    - resource:default/azurerm_postgresql_flexible_server_database.psql_db_metabase
    - resource:default/azurerm_postgresql_flexible_server_firewall_rule.psql_fw_rule
    - resource:default/postgresql_role.metabase_role

---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: postgresql_role.crawler_role
  description:  crawler_db_user
  resourceName: crawler_db_user
  resourceMode: managed
  resourceID: crawler_db_user

spec:
  type: postgresql_role
  owner: Marcos Cervantes
  system: Azure Terraform
  dependsOn: 
    - resource:default/azurerm_resource_group.resource_group
    - resource:default/azurerm_postgresql_flexible_server.postgresql_server
    - resource:default/azurerm_postgresql_flexible_server_firewall_rule.psql_fw_rule

---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: postgresql_role.metabase_role
  description:  metabase_db_user
  resourceName: metabase_db_user
  resourceMode: managed
  resourceID: metabase_db_user

spec:
  type: postgresql_role
  owner: Marcos Cervantes
  system: Azure Terraform
  dependsOn: 
    - resource:default/azurerm_resource_group.resource_group
    - resource:default/azurerm_postgresql_flexible_server.postgresql_server
    - resource:default/azurerm_postgresql_flexible_server_firewall_rule.psql_fw_rule

---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: azurerm_resource_group.resource_group
  description:  rg-wiki-pangea-agent-main-dev
  resourceName: rg-wiki-pangea-agent-main-dev
  resourceMode: managed
  resourceID: /subscriptions/fd3dc29c-3aef-4866-8f69-8ba0a9d31e42/resourceGroups/rg-wiki-pangea-agent-main-dev

spec:
  type: azurerm_resource_group
  owner: Marcos Cervantes
  system: Azure Terraform
  
---

